name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 213.199.38.183
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/controller-hub
            docker compose pull  halaqa-prod halaqa-staging
            docker compose up -d --no-deps  halaqa-prod halaqa-staging
            docker image prune -f
